### ISSUE TITLE
ValidationError on .spectral.yaml

### ISSUE THREAD

**Issue by vmarkovtsev** [IBM/openapi-validator#355]
I installed version 0.51.3 (0.52 does not see the Spectral config, see #354).
Wrote the following `.spectral.yaml` that I took [from the documentation](https://github.com/IBM/openapi-validator#changing-spectral-rule-severity):

```
extends: @ibm-cloud/openapi-ruleset
rules:
  openapi-tags: warn
```

The linter crashed.

```
$ lint-openapi -p -v openapi_rendered.yaml
[ValidationError: /extends should be array,string] {
  errors: [
    {
      keyword: 'type',
      dataPath: '/extends',
      schemaPath: '#/properties/extends/type',
      params: [Object],
      message: 'should be array,string'
    }
  ],
  validation: true,
  ajv: true
}
```

I added the quotes around `@ibm-cloud/openapi-ruleset` in `.spectral.yaml`

```
extends: '@ibm-cloud/openapi-ruleset'
rules:
  openapi-tags: warn
```

and hit

```
Error: Provided ruleset is not an object
    at Object.assertValidRuleset (/usr/lib/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral/dist/rulesets/validation.js:23:15)
    at processRuleset (/usr/lib/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral/dist/rulesets/reader.js:74:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async processRuleset (/usr/lib/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral/dist/rulesets/reader.js:92:39)
    at async Object.readRuleset (/usr/lib/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral/dist/rulesets/reader.js:29:33)
    at async Spectral.loadRuleset (/usr/lib/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral/dist/spectral.js:155:25)
    at async Object.setup (/usr/lib/node_modules/ibm-openapi-validator/src/spectral/utils/spectral-validator.js:81:3)
    at async processInput (/usr/lib/node_modules/ibm-openapi-validator/src/cli-validator/runValidator.js:177:5)
```

I guess the problem I have boils down to updating the documentation to include the single quotes in `extends`.

**Comment by dpopp07** [comment]
@vmarkovtsev your doc changes are now merged in. However, it looks like you were still having an issue (`Provided ruleset is not an object`) after putting quotes around the ruleset. Is that still happening for you with a valid ruleset?

**Comment by vmarkovtsev** [comment]
@dpopp07 That was for an older version of the validator. The latest version worked fine.
