### ISSUE TITLE
RulesetValidationError: Provided ruleset is not an object

### ISSUE THREAD

**Issue by tschaffter** [IBM/openapi-validator#521]
I'm upgrading to ibm-openapi-validator v0.96.4 (latest) and face the following error. It looks like the openapi-validator is not passing a valid ruleset to spectral.

```console
$ lint-openapi --ruleset .spectral.yaml --verbose build/user.openapi.yaml --debug
'lodash/isPlainObject' is imported by lodash/isPlainObject?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/isEqual' is imported by lodash/isEqual?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/uniqWith' is imported by lodash/uniqWith?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/pickBy' is imported by lodash/pickBy?commonjs-external, but could not be resolved – treating it as an external dependency

[Error] There was a problem with spectral.
Provided ruleset is not an object


[Error] Additional error details:

RulesetValidationError: Provided ruleset is not an object
    at assertValidRuleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/ruleset/validation/assertions.js:12:15)
    at new Ruleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/ruleset/ruleset.js:35:44)
    at Spectral.setRuleset (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/node_modules/@stoplight/spectral-core/dist/spectral.js:66:73)
    at Object.setup (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/src/spectral/spectral-validator.js:78:12)
    at async processInput (/workspaces/challenge-registry/node_modules/ibm-openapi-validator/src/cli-validator/run-validator.js:223:24) {
  code: 'invalid-ruleset-definition',
  path: []
}
```

`.spectral.yaml`:

```yaml
extends: '@ibm-cloud/openapi-ruleset'
# rules:
#   parameter-case-convention: info
```

Related to configuration, has this project drop the option to customize rules inside a json config file? The documentation provides an example to customize a rule with JS code in `.spectral.js`. Is that the only way now to customize rules?

Versions installed:

```console
"ibm-openapi-validator@npm:0.96.4":
  version: 0.96.4
  resolution: "ibm-openapi-validator@npm:0.96.4"
  dependencies:
    "@ibm-cloud/openapi-ruleset": 0.44.3
    "@stoplight/spectral-cli": ^6.4.2
    "@stoplight/spectral-core": ^1.12.4
    "@stoplight/spectral-parsers": ^1.0.1
```

**Comment by dpopp07** [comment]
@tschaffter Interesting, I've not seen that. I'll try to reproduce.

> Related to configuration, has this project drop the option to customize rules inside a json config file?

This project now supports only Spectral configuration files, which can be YAML, JSON, or JS formatted. As far as the additional configuration that used to be available through the `.validaterc` file, that is no longer supported. Complex customization of rules require JS code

**Comment by tschaffter** [comment]
I have the same issue when linting the [OpenAPI description of GitHub API](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml).

```console
$ lint-openapi --ruleset .spectral.yaml --verbose build/api.github.com.yaml
'lodash/isPlainObject' is imported by lodash/isPlainObject?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/isEqual' is imported by lodash/isEqual?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/uniqWith' is imported by lodash/uniqWith?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/pickBy' is imported by lodash/pickBy?commonjs-external, but could not be resolved – treating it as an external dependency

[Error] There was a problem with spectral.
Provided ruleset is not an object
```

**Comment by dpopp07** [comment]
@tschaffter Sorry to lose track of this issue. Are you still experiencing the problem in version 1.x?

**Comment by tschaffter** [comment]
Thanks for the message, @dpopp07 . I will give it another try and share the resuls.

**Comment by tschaffter** [comment]
Reinstalling the tool worked:

```
yarn remove ibm-openapi-validator
yarn add ibm-openapi-validator@1.0.7 -D
node_modules/.bin/lint-openapi openapi.yaml
```

The validator is now working.

The program still shows messages about lodash but that does seem to affect the output. Have you ever seen these messages?

```console
$ lint-openapi --config openapi-lint-config.yaml --ruleset spectral.yaml build/image.openapi.yaml                  
IBM OpenAPI Validator (validator: 1.0.7; ruleset: 1.0.4), @Copyright IBM Corporation 2017, 2023.

Validation Results for build/image.openapi.yaml:

'lodash/isPlainObject' is imported by lodash/isPlainObject?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/isEqual' is imported by lodash/isEqual?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/uniqWith' is imported by lodash/uniqWith?commonjs-external, but could not be resolved – treating it as an external dependency
'lodash/pickBy' is imported by lodash/pickBy?commonjs-external, but could not be resolved – treating it as an external dependency
Errors:

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.ImageHeight.enum.1
  Line    :   52

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.ImageHeight.enum.2
  Line    :   53
```

Otherwise the issue has been resolved and this ticket can be closed. Thanks again for developing this great tool!

**Comment by dpopp07** [comment]
> The program still shows messages about lodash but that does seem to affect the output. Have you ever seen these messages?

Yes, I have seen those. I've poked around a little but haven't had time for a full investigation. I'd like to try and get resolved soon.

For what it's worth, the logs don't print for me when I use a JS-formatted ruleset. e.g.
```js
const ibm = require('@ibm-cloud/openapi-ruleset');

module.exports = {
  extends: ibm,
  rules: {
    'ibm-parameter-casing-convention': 'info',
  },
};
```
So that may be a temporary alleviation.

> Thanks again for developing this great tool!

You're welcome, I'm glad that it's been useful to you!
