### ISSUE TITLE
Path with dot:  Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by apestov** [IBM/openapi-validator#53]
##### VERSION
ibm-openapi-validator: 0.9.1

##### SUMMARY
Validator fails with `Cannot read property '$ref' of undefined`  on path with dot and requestBody like:
```
  /dot.name:
    post:
      summary: Summary
      requestBody:
        content:
```

##### STACK TRACE
```
TypeError: Cannot read property '$ref' of undefined
    at each (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\oas3\semantic-validators\operations.js:62:69)
    at C:\example\node_modules\lodash\_createBaseFor.js:17:11
    at baseForOwn (C:\example\node_modules\lodash\_baseForOwn.js:13:20)
    at C:\example\node_modules\lodash\_createBaseEach.js:17:14
    at forEach (C:\example\node_modules\lodash\forEach.js:38:10)
    at each (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\oas3\semantic-validators\operations.js:26:5)
    at C:\example\node_modules\lodash\_createBaseFor.js:17:11
    at baseForOwn (C:\example\node_modules\lodash\_baseForOwn.js:13:20)
    at C:\example\node_modules\lodash\_createBaseEach.js:17:14
    at forEach (C:\example\node_modules\lodash\forEach.js:38:10)
```

##### STEPS TO REPRODUCE
1. Create `example.yaml`
```
openapi: 3.0.0

paths:

  /dot.name:
    post:
      summary: Summary
      requestBody:
        content:
          application/json:
            schema:
              type: integer
      responses:
        default:
          description: nop
```

2. Launch validator
```
$ lint-openapi example.yaml

[Warning] No .validaterc file found. The validator will run in default mode.
To configure the validator, create a .validaterc file.

[Error] There was a problem with a validator.
Cannot read property '$ref' of undefined
```

##### Expected result
ibm-openapi-validator will not fail.

##### Additional info
If remove the dot from the path, the validator will successfully complete.

**Comment by dpopp07** [comment]
@apestov Thanks for the issue, I will look into getting this fixed
